# Generated by Django 3.0.6 on 2020-06-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200629_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pic'),
        ),
    ]
