# Generated by Django 3.0.6 on 2020-06-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200629_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('id',)},
        ),
    ]
