# Generated by Django 3.0.6 on 2020-07-09 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_auto_20200629_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-added_date',)},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('cat_id',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='img',
            field=models.ImageField(blank=True, upload_to='comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='clikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='vlikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
    ]
