# Generated by Django 3.0.6 on 2020-07-15 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_auto_20200710_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Pic',
            new_name='Profile_Pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='Cover_pic',
            field=models.ImageField(default='default1.jpg', upload_to='cover_pic'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Video')),
            ],
        ),
    ]
